// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqnvisznrqlrcnbdutmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxbnZpc3pucnFscmNuYmR1dG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1MDM0NTYsImV4cCI6MjA5MDA3OTQ1Nn0.zuncAxuJthKcBEPZAGznMOFzn_UIC4uqUP83ipHaHaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});